2019-04-01 #2

diff --git a/scripts/.local/bin/startpolybar b/scripts/.local/bin/startpolybar
--- a/scripts/.local/bin/startpolybar
+++ b/scripts/.local/bin/startpolybar
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
-if [ -f "$HOME/.config/polybar/start" ]; then
-  bash "$HOME/.config/polybar/start"
+if [ -f "$HOME/.config/polybar/launch" ]; then
+  bash "$HOME/.config/polybar/launch"
 else
-  echo "Polybar start script not found" >&2
+  echo "Polybar launch script not found" >&2
   exit 1
 fi
