emacs: Make scripts more robust

diff --git a/emacs/.local/bin/evil b/emacs/.local/bin/evil
--- a/emacs/.local/bin/evil
+++ b/emacs/.local/bin/evil
@@ -1,9 +1,17 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+set -euo pipefail
+IFS=$'\n\t'
+
+assert_exists() {
+  command -v "$1" >/dev/null 2>&1 || (echo "Missing executable $1" >&2; exit 1)
+}
+
+assert_exists greadlink
+assert_exists emacsclient
 
 export ALTERNATE_EDITOR=""
-
 export TERM=xterm-24bit
-
-emacsclient=$(greadlink -f "$(which emacsclient)")
+emacsclient=$(greadlink -f "$(command -v emacsclient)")
 
 exec "$emacsclient" -s tty --tty "$@"
