2019-08-16 #2

diff --git a/git/.config/git/scripts/git-rebase-back b/git/.config/git/scripts/git-rebase-back
--- a/git/.config/git/scripts/git-rebase-back
+++ b/git/.config/git/scripts/git-rebase-back
@@ -7,8 +7,17 @@ if [ -z "$1" ]; then
   exit 1
 elif echo "$1" | grep -Eq '^[0-9]+$'; then
   # If it's a number, work backwards from HEAD
-  git rebase --interactive "HEAD~$1" "${@:2}"
+  ref="HEAD~$1"
 else
   # If it's not a number, treat it like a normal ref
-  git rebase --interactive "$1" "${@:2}"
+  ref="$1"
 fi
+
+# Verify it's a valid ref
+if git rev-parse "$ref" --verify --quiet >/dev/null 2>&1; then
+  echo "Invalid ref '$ref'"
+  exit 1
+fi
+
+# Begin interactive rebase
+git rebase --interactive "$ref" "${@:2}"
